In [1]:
import pandas as pd
import numpy as np

In [2]:
air=pd.read_csv('air_quality_dataset.csv')
air.head()

,Date,City,AQI,PM2.5,PM10,Ozone,NO2,CO,SO2,Temperature,Humidity
0,2024-10-16,Los Angeles,128.0,28.78,68.84,58.29,57.56,2.781,17.10,3.4,82.2
1,2023-01-26,Jacksonville,111.0,28.73,61.93,59.00,35.73,1.810,16.33,17.0,36.0
2,2023-10-09,Houston,91.0,20.04,47.10,66.20,43.91,2.566,15.27,1.0,68.6
3,2023-08-17,Chicago,108.0,23.39,47.90,62.85,48.89,2.332,18.49,9.4,85.7
4,2023-04-15,Austin,106.0,26.51,56.08,62.38,NaN,1.867,15.93,17.3,48.7

In [3]:
air.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5583 entries, 0 to 5582
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         5583 non-null   object
 1   City         5583 non-null   object
 2   AQI          5472 non-null   float64
 3   PM2.5        5486 non-null   float64
 4   PM10         5523 non-null   float64
 5   Ozone        5508 non-null   float64
 6   NO2          5490 non-null   float64
 7   CO           5421 non-null   float64
 8   SO2          5454 non-null   float64
 9   Temperature  5435 non-null   float64
 10  Humidity     5479 non-null   float64
dtypes: float64(9), object(2)
memory usage: 479.9+ KB

In [4]:
#Data cleaning
#cheak missing value
print(air.isnull().sum())

Date             0
City             0
AQI            111
PM2.5           97
PM10            60
Ozone           75
NO2             93
CO             162
SO2            129
Temperature    148
Humidity       104
dtype: int64

In [5]:
air.fillna(air.mode().iloc[0], inplace=True)  #filled null values

In [6]:
#remove duplicates
air.drop_duplicates(inplace=True)

In [7]:
#data after data cleaning
print(air.isnull().sum())

Date           0
City           0
AQI            0
PM2.5          0
PM10           0
Ozone          0
NO2            0
CO             0
SO2            0
Temperature    0
Humidity       0
dtype: int64

In [8]:
# Split dataset into two parts
data1 = air[['Date', 'City', 'AQI']]
data2 = air[['PM2.5', 'PM10', 'Ozone', 'NO2', 'CO', 'SO2', 'Temperature', 'Humidity']]

In [9]:
integrated_data = pd.concat([data1, data2], axis=1)

In [10]:
print(integrated_data.head())

         Date          City    AQI  PM2.5   PM10  Ozone    NO2     CO    SO2  \
0  2024-10-16   Los Angeles  128.0  28.78  68.84  58.29  57.56  2.781  17.10
1  2023-01-26  Jacksonville  111.0  28.73  61.93  59.00  35.73  1.810  16.33
2  2023-10-09       Houston   91.0  20.04  47.10  66.20  43.91  2.566  15.27
3  2023-08-17       Chicago  108.0  23.39  47.90  62.85  48.89  2.332  18.49
4  2023-04-15        Austin  106.0  26.51  56.08  62.38  40.52  1.867  15.93

   Temperature  Humidity
0          3.4      82.2
1         17.0      36.0
2          1.0      68.6
3          9.4      85.7
4         17.3      48.7

In [11]:
air['Date'] = pd.to_datetime(air['Date'])
air.head()

,Date,City,AQI,PM2.5,PM10,Ozone,NO2,CO,SO2,Temperature,Humidity
0,2024-10-16,Los Angeles,128.0,28.78,68.84,58.29,57.56,2.781,17.10,3.4,82.2
1,2023-01-26,Jacksonville,111.0,28.73,61.93,59.00,35.73,1.810,16.33,17.0,36.0
2,2023-10-09,Houston,91.0,20.04,47.10,66.20,43.91,2.566,15.27,1.0,68.6
3,2023-08-17,Chicago,108.0,23.39,47.90,62.85,48.89,2.332,18.49,9.4,85.7
4,2023-04-15,Austin,106.0,26.51,56.08,62.38,40.52,1.867,15.93,17.3,48.7

In [12]:
#lable Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
air['City'] = le.fit_transform(air['City'])

In [13]:
air.head()

,Date,City,AQI,PM2.5,PM10,Ozone,NO2,CO,SO2,Temperature,Humidity
0,2024-10-16,8,128.0,28.78,68.84,58.29,57.56,2.781,17.10,3.4,82.2
1,2023-01-26,7,111.0,28.73,61.93,59.00,35.73,1.810,16.33,17.0,36.0
2,2023-10-09,6,91.0,20.04,47.10,66.20,43.91,2.566,15.27,1.0,68.6
3,2023-08-17,2,108.0,23.39,47.90,62.85,48.89,2.332,18.49,9.4,85.7
4,2023-04-15,0,106.0,26.51,56.08,62.38,40.52,1.867,15.93,17.3,48.7

In [14]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numeric_cols = ['AQI','PM2.5','PM10','Ozone','NO2','CO','SO2','Temperature','Humidity']
air[numeric_cols] = scaler.fit_transform(air[numeric_cols])
air.head()

,Date,City,AQI,PM2.5,PM10,Ozone,NO2,CO,SO2,Temperature,Humidity
0,2024-10-16,8,0.669445,0.215533,0.767185,-0.469215,1.315151,0.607594,0.175793,-1.000036,1.036219
1,2023-01-26,7,-0.040066,0.211277,0.325004,-0.424809,-0.661577,-0.344718,0.075208,0.147835,-1.095889
2,2023-10-09,6,-0.874784,-0.528344,-0.623991,0.025512,0.079130,0.396732,-0.063261,-1.202602,0.408586
3,2023-08-17,2,-0.165273,-0.243220,-0.572798,-0.184012,0.530074,0.167235,0.357370,-0.493622,1.197743
4,2023-04-15,0,-0.248745,0.022329,-0.049347,-0.213408,-0.227838,-0.288815,0.022955,0.173156,-0.509790

In [15]:
print((air[['AQI','PM2.5','PM10','Ozone','NO2','CO','SO2']] < 0).sum())

AQI      2925
PM2.5    3079
PM10     2969
Ozone    3175
NO2      2928
CO       2987
SO2      2909
dtype: int64

In [16]:
#fix negative value
air.fillna(air.mean(), inplace=True)

In [23]:
def categorize_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    else:
        return "Poor"

air['AQI_Level'] = air['AQI'].apply(categorize_aqi)

In [24]:
#Select Features (X) and Target (y)
X = air[['PM2.5','PM10','Ozone','NO2','CO','SO2','Temperature','Humidity']]
y = air['AQI_Level']

In [25]:
#Split Data into Training and Testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [26]:
#choose model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Features
X = air[['PM2.5','PM10','Ozone','NO2','CO','SO2','Temperature','Humidity']]

# Target
y = air['AQI']

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MSE: 0.4897384665856287
R2 Score: 0.45453261207343

In [27]:
print(air['AQI_Level'].value_counts())

AQI_Level
Good    5497
Name: count, dtype: int64